# Generated by Django 6.1.1 on 2026-09-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Media/Fotos')),
                ('documentos', models.FileField(blank=True, null=True, upload_to='Media/Documentos')),
                ('audio', models.FileField(blank=True, null=True, upload_to='Media/Audios')),
                ('video', models.FileField(blank=True, null=True, upload_to='Media/Videos')),
                ('reporte', models.FileField(blank=True, null=True, upload_to='Media/Reportes')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
