# Generated by Django 6.1.1 on 2026-09-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evacuacion_coderider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='reportes/audios/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='reportes/documentos/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='reportes/fotos/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='reporte',
            field=models.FileField(blank=True, null=True, upload_to='reportes/archivos/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reportes/videos/'),
        ),
    ]
