# Generated by Django 6.1 on 2026-08-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temblor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitud', models.FloatField()),
                ('profundidad', models.FloatField()),
                ('rango', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
