# Generated by Django 6.1 on 2026-08-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_capacitacion', models.CharField(max_length=255)),
                ('duracion', models.CharField(max_length=100)),
                ('tipo_capacitacion', models.CharField(max_length=100)),
                ('detalles', models.TextField()),
            ],
        ),
    ]
