# Generated by Django 6.1.1 on 2026-09-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usgs_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('magnitud', models.FloatField(db_index=True)),
                ('lugar', models.CharField(max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('profundidad', models.FloatField(help_text='Profundidad en Kilómetros')),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('tsunami', models.BooleanField(default=False)),
                ('alerta', models.CharField(default='none', max_length=20)),
                ('estado', models.CharField(default='reviewed', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sismo',
                'verbose_name_plural': 'Sismos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
