# Generated by Django 6.1 on 2026-08-26 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDePago',
            fields=[
                ('id_tipo_de_pago', models.AutoField(db_column='idTipo de Pago', primary_key=True, serialize=False)),
                ('efectivo', models.DecimalField(blank=True, db_column='Efectivo', decimal_places=2, max_digits=12, null=True)),
                ('transferencia', models.DecimalField(blank=True, db_column='Transferencia', decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'Tipo de Pago',
            },
        ),
        migrations.CreateModel(
            name='PagosEntrega',
            fields=[
                ('id_pago_entrega', models.BigAutoField(db_column='idPago Entrega', primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(db_column='Valor Total', decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('OTRO', 'Otro')], db_column='Metodo Pago', max_length=50)),
                ('evidencia_url', models.CharField(blank=True, db_column='Evidencia Url', max_length=255, null=True)),
                ('fecha_de_pago', models.DateTimeField(db_column='Fecha De Pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], db_column='Estado', max_length=50)),
                ('tipo_de_pago', models.ForeignKey(db_column='Tipo de Pago_idTipo de Pago', on_delete=django.db.models.deletion.CASCADE, to='app_PagosEntrega_TipoPago.tipodepago')),
            ],
            options={
                'db_table': 'Pagos Entrega',
            },
        ),
    ]
