# Generated by Django 6.1 on 2026-09-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PagosEntrega_TipoPago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.BigAutoField(db_column='idEntrega', primary_key=True, serialize=False)),
                ('codigo_guia', models.CharField(db_column='Codigo Guia', max_length=100, unique=True)),
                ('direccion_destino', models.CharField(db_column='Direccion Destino', max_length=255)),
            ],
            options={
                'db_table': 'Entrega',
            },
        ),
        migrations.RemoveField(
            model_name='pagosentrega',
            name='evidencia_url',
        ),
        migrations.AlterField(
            model_name='pagosentrega',
            name='tipo_de_pago',
            field=models.ForeignKey(db_column='Tipo de Pago_idTipo de Pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app_PagosEntrega_TipoPago.tipodepago'),
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id_comprobante', models.BigAutoField(db_column='idComprobante', primary_key=True, serialize=False)),
                ('numero_transaccion', models.CharField(db_column='Numero Transaccion', max_length=100, unique=True)),
                ('evidencia_url', models.CharField(blank=True, db_column='Evidencia Url', max_length=255, null=True)),
                ('pago_entrega', models.OneToOneField(db_column='Pagos Entrega_idPago Entrega', on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='app_PagosEntrega_TipoPago.pagosentrega')),
            ],
            options={
                'db_table': 'Comprobante Pago',
            },
        ),
        migrations.AddField(
            model_name='pagosentrega',
            name='entregas',
            field=models.ManyToManyField(db_table='Pagos_x_Entrega', related_name='pagos', to='app_PagosEntrega_TipoPago.entrega'),
        ),
    ]
